### ISSUE TITLE
can't read locations

### ISSUE THREAD

**Issue by brenzi** [encointer/explorer#81]
```
Map.js:191 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getLocations')
    at Map.js:191:13
    at Map.js:429:7
    at Hu (react-dom.production.min.js:262:359)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Wi (react-dom.production.min.js:122:325)
    at Vu (react-dom.production.min.js:261:308)
    at bu (react-dom.production.min.js:243:50)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Wi (react-dom.production.min.js:122:325)
```

**Comment by brenzi** [comment]
that one is probably caused by the outdated rpc node, running v1.0.1 (old rpc prefix)
